### ISSUE TITLE
Colony models not found

### ISSUE THREAD

**Issue by 0something0** [briligg/Moonwards-Virtual-Moon#30]
The 3D model downloads for blender/GDot develpment (Version for development in Blender/Version for export to Godot) are broken. It says the files do not exist.

**Comment by MolbOrg** [comment]
@0something0 Would you like to provide an example of some specific file and which file it says does no exist?

**Comment by briligg** [comment]
Thanks for catching that 0something0. I failed to update the website to remove those links after i instead linked to this repository. 

The thing to do is download the zip of this repo or clone it to use it with git. That will provide you with everything.

Sorry for the inconvenience, i'll fix that.

**Comment by 0something0** [comment]
@MolbOrg  https://www.moonwards.com/project.html#assets

![image](https://user-images.githubusercontent.com/23426461/56086349-1b83ce80-5e23-11e9-8490-160581c94759.png)

**Comment by briligg** [comment]
The master file for the current state of the project is not complete for Blender. Instead all the models are in separate files that have not been fully linked into the file of the full colony. We got busy with other things...

Let me know if you have any trouble finding what you need or want the full town rebuilt in Blender, and i'll bump it up the list of tasks.

**Comment by 0something0** [comment]
I was looking for the full town rebuilt, though I would be happy with an outdated version.

**Comment by briligg** [comment]
Happy with something outdated? Dear me

For the moment, the best i can offer is at this link:

https://github.com/briligg/Moonwards-Blender/blob/master/Cernans%20Promise/CernansPromise-BlenderVersion.blend
