### ISSUE TITLE
Player movement - sudden displacement when running or exaggerated response

### ISSUE THREAD

**Issue by briligg** [briligg/Moonwards-Virtual-Moon#32]
When running, the player sometimes suddenly moves forwards by 10 to 30 meters. This can happen while jumping, which causes the player to go much further than intended. 

This issue has proven hard to resolve in a stable, long-term way. Current partially successful fixes aren't sufficient to properly tour people through the town.

**Comment by Gyrth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Player movement - sudden displacement when running or exaggerated response](https://trello.com/c/xuhUd0Kg/19-player-movement-sudden-displacement-when-running-or-exaggerated-response)
