### ISSUE TITLE
Add Godot Slides to Multimedia Buttons

### ISSUE THREAD

**Issue by briligg** [briligg/Moonwards-Virtual-Moon#9]
This may call for a new repo dedicated to such slides.

https://github.com/GDquest/godot-slides

**Comment by yaelatletl** [comment]
I propose using 2d in 3d with viewports

**Comment by briligg** [comment]
Do you have an example for that?

**Comment by yaelatletl** [comment]
https://github.com/godotengine/godot-demo-projects/tree/master/viewport/gui_in_3d 
Here, this can be helpful, creates an interface in 2d and displays it as a plane in 3d
I've done it to make it look like a screen 
![imagen](https://user-images.githubusercontent.com/28612272/47967174-38200d00-e020-11e8-9a24-783a88c2744f.png)
